test

diff --git a/.github/workflows/job-build-push-image.yml b/.github/workflows/job-build-push-image.yml
--- a/.github/workflows/job-build-push-image.yml
+++ b/.github/workflows/job-build-push-image.yml
@@ -25,22 +25,14 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v3
 
-      - name: Debug Secrets
-        env:
-          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
-          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
-        run: |
-          echo "DOCKER_USERNAME: ${DOCKER_USERNAME}"
-          echo "DOCKER_PASSWORD length: ${#DOCKER_PASSWORD}"
-
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
 
       - name: Login to Docker Hub
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
+        run: |
+          set -e
+          echo "Logging in to Docker Hub"
+          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
       - name: Build and push Docker image
         run: |
@@ -49,12 +41,11 @@ jobs:
           TAG=${{ github.sha }}
 
           echo "Building Docker image with tag: $TAG"
-          docker build --cache-from=type=registry,ref=$IMAGE_NAME:latest \
-                       --cache-to=type=inline \
-                       -t $IMAGE_NAME:$TAG .
-
-          echo "Pushing image to Docker Hub"
-          docker push $IMAGE_NAME:$TAG
+          docker buildx build \
+            --cache-from=type=registry,ref=$IMAGE_NAME:latest \
+            --cache-to=type=registry,ref=$IMAGE_NAME:build-cache,mode=max \
+            --tag $IMAGE_NAME:$TAG \
+            --push .
 
       - name: Tag and push latest image
         run: |
@@ -63,8 +54,10 @@ jobs:
           TAG=${{ github.sha }}
 
           echo "Tagging latest image"
-          docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest
-          docker push $IMAGE_NAME:latest
+          docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest || { echo "Tagging failed!"; exit 1; }
+
+          echo "Pushing latest image"
+          docker push $IMAGE_NAME:latest || { echo "Push failed!"; exit 1; }
 
       - name: Tag and push release versions
         if: startsWith(github.ref, 'refs/tags/')
@@ -73,6 +66,13 @@ jobs:
           IMAGE_NAME=asd2321s2/express-api
           TAG=${GITHUB_REF#refs/tags/}
 
+          if [[ -z "$TAG" ]]; then
+            echo "Invalid tag. Exiting..."
+            exit 1
+          fi
+
           echo "Tagging release version: $TAG"
-          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:$TAG
-          docker push $IMAGE_NAME:$TAG
+          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:$TAG || { echo "Tagging failed!"; exit 1; }
+
+          echo "Pushing release image"
+          docker push $IMAGE_NAME:$TAG || { echo "Push failed!"; exit 1; }
